name: Demo Web Shop Automation Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  automation-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven Packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Run Selenium Tests
        working-directory: automation-testing/DemoWebShop_AutomationTesting
        run: mvn clean test