name: REST Assured API Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  api-testing:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven Packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      - name: Run API Tests
        working-directory: API-Testing/Rest-Assured
        run: mvn clean test
